server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # The magic line that makes React Router work on page refreshes
        try_files $uri $uri/ /index.html;
    }
}