services:
  # --- 1. POSTGRES DATABASE ---
  db:
    image: postgres:15-alpine
    container_name: campus-db
    restart: always
    environment:
      POSTGRES_USER: campus_app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: CampusCompile_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- 2. REDIS MESSAGE QUEUE ---
  redis:
    image: redis:alpine
    container_name: campus-redis
    restart: always
    ports:
      - "6379:6379"

  # --- 3. GO API BACKEND ---
  api:
    build: 
      context: ./server  # Looks for a Dockerfile in your 'server' folder
    container_name: campus-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      - DB_HOST=db       # Go will connect to 'db' instead of 'localhost'
      - REDIS_HOST=redis # Go will connect to 'redis' instead of 'localhost'

  # --- 4. PYTHON EXECUTION WORKER ---
  worker:
    build: 
      context: ./worker        # Looks for a Dockerfile where queue_listener.py is
    container_name: campus-worker
    depends_on:
      - db
      - redis
    volumes:
      # Gives Python access to the host's Docker engine
      - /var/run/docker.sock:/var/run/docker.sock 
      # Give the worker access to the shared sandbox drive
      - sandbox_volume:/sandbox_shared
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  # --- 5. REACT FRONTEND ---
  frontend:
    build:
      context: ./frontend
    container_name: campus-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080

# Define the persistent storage for Postgres
volumes:
  pgdata:
  sandbox_volume:
    name: sandbox_volume