services:
  # --- 1. POSTGRES DATABASE ---
  db:
    image: postgres:15-alpine
    container_name: campus-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: CampusCompile_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - shm_size: 1g

  # --- 2. REDIS MESSAGE QUEUE ---
  redis:
    image: redis:alpine
    container_name: campus-redis
    restart: always
    command: redis-server --appendonly yes

  # --- 3. GO API BACKEND ---
  api:
    build:
      context: ./server
    container_name: campus-api
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://minio:9000

  # --- 4. PYTHON EXECUTION WORKER ---
  worker:
    build:
      context: ./worker
    container_name: campus-worker
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /sandbox_shared:exec,mode=777
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://minio:9000
    user: root

  # --- 5. REACT FRONTEND ---
  frontend:
    container_name: campus-frontend

  # --- 6. MINIO STORAGE ---
  minio:
    image: minio/minio
    container_name: campus-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
