FROM python:3.11-alpine

RUN addgroup -g 1001 student_group && \
    adduser -D -u 1001 -G student_group student

RUN mkdir -p /sandbox_shared && chown student:student_group /sandbox_shared

WORKDIR /sandbox_shared

USER student

CMD ["/bin/sh"]